export default Object.freeze({
  NIETALLEEN_API_HOST: process.env.NIETALLEEN_API_HOST,
  NIETALLEEN_API_ENDPOINT_MAILFORM: process.env.NIETALLEEN_API_ENDPOINT_MAILFORM,
  NIETALLEEN_API_ENDPOINT_LOCATIONS: process.env.NIETALLEEN_API_ENDPOINT_LOCATIONS,
  NIETALLEEN_API_ENDPOINT_HUBS: process.env.NIETALLEEN_API_ENDPOINT_HUBS
})
