[build]
    command = "npm run generate"
    publish = "dist"

[context.production.environment]
    URL = "https://nietalleen.nl"

[context."develop".environment]
#   Overwrite API host for develop branch/app
    NIETALLEEN_API_HOST = "https://test-api-nietalleen.eo.nl"
    URL = "https://develop.nietalleen.nl"

[context.deploy-preview.environment]
#    NODE_ENV = "development"
    URL = "https://develop.nietalleen.nl"

[[redirects]]
  from = "/*"
  to = "https://www.eo.nl/programmas/niet-alleen-nl"
  status = 200
  force = true
