[build]
    command = "npm run generate"
    publish = "dist"

[context.production.environment]
    URL = "https://nietalleen.nl"

[context."develop".environment]
    URL = "https://develop.nietalleen.nl"

[context.deploy-preview.environment]
#    NODE_ENV = "development"
    URL = "${DEPLOY_PRIME_URL}"